### PR TITLE
Suggest Zero-config of the wpstart snippet

### PR DESCRIPTION
**Pull request by doggy8088**
Zero-config is a trend.  I made a PR for your `wpstart` snippets.  Please take consideration of this.  You can totally ignore my suggestion if you don't agree.  Thanks! :)

### CODE REVIEW

**Comment by LiShiSangZi** [comment]
@doggy8088 I am very happy about your PR. I agree that zero config is an interesting feature for the latest webpack. But I think we need to add some new snippets for those new features instead of replacing the old. Do you have any ideal?

Thanks again for your PR.

**Comment by doggy8088** [comment]
@LiShiSangZi You are very welcome! :-) 

Do you mean you want to add more webpack config snippets for zero-config in mind?  Maybe a new snippet just like `wpstart2`?

**Comment by LiShiSangZi** [comment]
Yes. Because I think webpack4 is quit different from 3 because of zero config. Compatible with old version is necessary.

**Comment by doggy8088** [comment]
Well, I'm not talking about the webpack 4 at the beginning.  My original concept is just webpack 3's config become more  "zero-config" when using these code snippets.

**Comment by LiShiSangZi** [comment]
My bad. I misunderstand the it.

I agree your update is much better than the original code. Thanks a lot!

**Comment by doggy8088** [comment]
Wow, that's quick!  Thanks for merging! 👍

**Pull request merged**
